### ISSUE TITLE
rand.Seed should be replaced with rand.NewSource

### ISSUE THREAD

**Issue by pan93412** [19byte/goobfuscated#1]
According to Go Docs ([rand package - math/rand - Go Packages](https://pkg.go.dev/math/rand#Seed)):

> Deprecated: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.

**Comment by 19byte** [comment]
thank you very much,it has been revised 👉👈
